name: GCCBuild

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  OSTYPE: Linux
  CACHE_VERSION: 1
  BOOST_VERSION: 1.78.0
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    steps:
    - name: Processor Property
      run: lscpu

    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
        
    - name: Checkout submodule
      run: |
        git submodule init
        git submodule update

    - name: Install opencv
      run: |
        sudo apt-get update
        sudo apt-get install libopencv-dev

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmake .
        cmake --build .