name: MSBuild

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  
  OSTYPE: Windows

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 20

    steps:
    - name: Processor Property
      run: Get-CimInstance -ClassName Win32_Processor | Select-Object -ExcludeProperty "CIM*"

    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2

    - name: Install opencv
      uses: cvpkg/opencv-action@v0.1
      with:
        opencv_tag: '4.6.0' # Optional. Default is '4.6.0'. An env var 'opencv_tag' will be defined.
        BUILD_LIST: 'core,imgcodecs,imgproc' # Optional. Default is 'core,imgcodecs,imgproc'. The opencv modules(libraries, components) to be build, separated with `,` and no spaces.
        BUILD_SHARED_LIBS: 'OFF' # Optional. Default is 'OFF'. Build shared opencv librarires, should be "ON" or "OFF".
        BUILD_WITH_STATIC_CRT: 'OFF' # Optional. Default is 'OFF'. Build with static C Runtime Library?(only when MSVC), should be "ON" or "OFF"
    
    - name: Checkout submodule
      run: |
        git submodule init
        git submodule update

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmake .
        cmake --build .